Task "StackCalculator" from homework 2
Salvatore112/SPBU-ProgrammingHW-Semester2 pull request #6
Opened 2023-03-05 14:35 UTC by Salvatore112

2023-03-09 15:42 UTC, yurii-litvinov requested changes

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/Program.cs
> +    {
Это не надо

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/Program.cs
> +    interface IStack
Это должно быть в отдельном файле и на верхнем уровне

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +    Exception StackOverflowException = new Exception("Stack exceeded its capacity!");
Не-а, так никто не делает

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +    int Capacity { get { return capacity; } }
И так. Не пользуйтесь языковыми конструкциями, которых не понимаете.

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +            throw StackOverflowException;
Не, надо, чтобы стек менял свой размер в этом случае. А то не интересно :)

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +        size--;
Кажется, у Вас всегда `stackPosition == size - 1`, что делает одно из них ненужным

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +    }
```suggestion
    public bool IsEmpty()
        => stackPosition == 0;
```

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +        this.size = 0;
Это не надо

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/ListStack.cs
> +}
Тут в принципе те же замечания, потому что и код по сути тот же

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator.cs
> +    int GetNextNumber(string Expression, ref int i)
Параметры именуются в camelCase

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator.cs
> +        var Stack = new ListStack();
`Стековый калькулятор должен знать только про интерфейс стека (то есть вообще в коде класса «Стековый калькулятор» не должно быть ни одного упоминания конкретных реализаций стека, даже если очень хочется).`

Вообще, это невыполнение требований условия :)

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator.cs
> +        }
string.Split сделало бы это лучше

2023-03-09 15:42 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator.cs
> +                    if (bottomElement - 0 < 0.000001)
`- 0` не очень мне нравится. Алгебра говорит, что это тождественная функция.

2023-03-10 11:29 UTC, AmarskiyArtem commented on Homework2/StackCalculator/StackCalculator.cs
> +                    if (bottomElement - 0 < 0.000001)
кажется на отрицательных числах программа с ужасом упадет

2023-03-13 11:38 UTC, yurii-litvinov approved these changes
Не очень аккуратно, но вполне ок. Зачтена.

2023-03-13 11:38 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +internal class ArrayStack : IStack
Надо комментарий

2023-03-13 11:38 UTC, yurii-litvinov commented on Homework2/StackCalculator/ArrayStack.cs
> +    public ArrayStack (int capacity)
```suggestion
    public ArrayStack(int capacity)
```

2023-03-13 11:38 UTC, yurii-litvinov commented on Homework2/StackCalculator/Program.cs
> +
```suggestion
```

2023-03-13 11:38 UTC, yurii-litvinov commented on Homework2/StackCalculator/Program.cs
> +}
```suggestion
    Console.WriteLine("Tests weren't passed");         
}
```

2023-03-17 19:19 UTC, merged